### ISSUE TITLE
cannot load such file -- rails (LoadError)

### ISSUE THREAD

**Issue by ksimmi** [karafka/karafka#2366]
Hello,

I'm trying to start a new non-Rails project using Karafka and the standalone_migrations gem. My app is very simple at the moment, with no logic implemented yet—just basic ping-pong functionality. However, when I added the standalone_migrations gem to my Gemfile, I immediately encountered an error.

```
bundler: failed to load command: karafka (/usr/local/bundle/ruby/3.2.0/bin/karafka)
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- rails (LoadError)
 from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
 from /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
 from /usr/local/bundle/ruby/3.2.0/gems/standalone_migrations-2.0.4/lib/standalone_migrations.rb:5:in `<top (required)>'
 from /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
 from /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
 from /usr/local/bundle/gems/bundler-2.5.14/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
 from /usr/local/bundle/gems/bundler-2.5.14/lib/bundler/runtime.rb:55:in `each'
 from /usr/local/bundle/gems/bundler-2.5.14/lib/bundler/runtime.rb:55:in `block in require'
 from /usr/local/bundle/gems/bundler-2.5.14/lib/bundler/runtime.rb:44:in `each'
 from /usr/local/bundle/gems/bundler-2.5.14/lib/bundler/runtime.rb:44:in `require'
 from /usr/local/bundle/gems/bundler-2.5.14/lib/bundler.rb:212:in `require'
 from /app/karafka.rb:6:in `<top (required)>'
 from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
 from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
 from /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
 from /usr/local/bundle/ruby/3.2.0/gems/karafka-2.4.15/lib/karafka/cli/base.rb:64:in `load'
 from /usr/local/bundle/ruby/3.2.0/gems/karafka-2.4.15/bin/karafka:9:in `<top (required)>'
 from /usr/local/bundle/ruby/3.2.0/bin/karafka:25:in `load'
 from /usr/local/bundle/ruby/3.2.0/bin/karafka:25:in `<top (required)>'
 from /usr/local/bundle/gems/bundler-2.5.14/lib/bundler/cli/exec.rb:58:in `load'
 from /usr/local/bundle/gems/bundler-2.5.14/lib/bundler/cli/exec.rb:58:in `kernel_load'
 from /usr/local/bundle/gems/bundler-2.5.14/lib/bundler/cli/exec.rb:23:in `run'
 from /usr/local/bundle/gems/bundler-2.5.14/lib/bundler/cli.rb:455:in `exec'
 from /usr/local/bundle/gems/bundler-2.5.14/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
 from /usr/local/bundle/gems/bundler-2.5.14/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
 from /usr/local/bundle/gems/bundler-2.5.14/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
 from /usr/local/bundle/gems/bundler-2.5.14/lib/bundler/cli.rb:35:in `dispatch'
 from /usr/local/bundle/gems/bundler-2.5.14/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
 from /usr/local/bundle/gems/bundler-2.5.14/lib/bundler/cli.rb:29:in `start'
 from /usr/local/bundle/gems/bundler-2.5.14/exe/bundle:28:in `block in <top (required)>'
 from /usr/local/bundle/gems/bundler-2.5.14/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
 from /usr/local/bundle/gems/bundler-2.5.14/exe/bundle:20:in `<top (required)>'
 from /usr/local/bundle/bin/bundle:25:in `load'a
 from /usr/local/bundle/bin/bundle:25:in `<main>'
```

How to use the both gems together?

Thank you.

**Comment by mensfeld** [comment]
I don't know. Please follow the reporting guidelinues if you want me to pick it up: https://karafka.io/docs/Support/#issue-reporting-guide

**Comment by ksimmi** [comment]
Ruby and Docker container
```
ARG RUBY_VERSION=3.2.2
FROM registry.docker.com/library/ruby:$RUBY_VERSION-slim as base
...
```
OS
```
uname -a
Linux 667150deeceb 5.4.0-200-generic #220-Ubuntu SMP Fri Sep 27 13:19:16 UTC 2024 x86_64 GNU/Linux
```

karafka.rb Content
```
# frozen_string_literal: true

# This is a non-Rails example app!

ENV['KARAFKA_ENV'] ||= 'development'
Bundler.require(:default, ENV['KARAFKA_ENV'])

# Zeitwerk custom loader for loading the app components before the whole
# Karafka framework configuration
APP_LOADER = Zeitwerk::Loader.new

%w[
  consumers
].each(&APP_LOADER.method(:push_dir))

APP_LOADER.setup
APP_LOADER.eager_load

# App class
class App < Karafka::App
  setup do |config|
    config.concurrency = 5
    config.max_wait_time = 1_000
    config.kafka = { 'bootstrap.servers': ENV['KAFKA_HOST'] || '127.0.0.1:9092' }
  end
end

Karafka.monitor.subscribe(Karafka::Instrumentation::LoggerListener.new)
Karafka.monitor.subscribe(Karafka::Instrumentation::ProctitleListener.new)
Karafka.producer.monitor.subscribe(
  WaterDrop::Instrumentation::LoggerListener.new(
    Karafka.logger,
    # If you set this to true, logs will contain each message details
    # Please note, that this can be extensive
    log_messages: false
  )
)

App.consumer_groups.draw do
  consumer_group :batched_group do
    topic :pong do
      # 1 day in ms
      config(partitions: 5, 'retention.ms': 86_400_000)
      consumer Pong::PongConsumer
    end
  end
end
```

Gemfile
```
# frozen_string_literal: true

source 'https://rubygems.org'

gem 'karafka'
gem 'standalone_migrations'
gem 'pg'
```

Gemfile.lock
```
GEM
  remote: https://rubygems.org/
  specs:
    base64 (0.2.0)
    ffi (1.17.0)
    ffi (1.17.0-aarch64-linux-gnu)
    ffi (1.17.0-aarch64-linux-musl)
    ffi (1.17.0-arm-linux-gnu)
    ffi (1.17.0-arm-linux-musl)
    ffi (1.17.0-arm64-darwin)
    ffi (1.17.0-x86-linux-gnu)
    ffi (1.17.0-x86-linux-musl)
    ffi (1.17.0-x86_64-darwin)
    ffi (1.17.0-x86_64-linux-gnu)
    ffi (1.17.0-x86_64-linux-musl)
    karafka (2.4.15)
      base64 (~> 0.2)
      karafka-core (>= 2.4.4, < 2.5.0)
      karafka-rdkafka (>= 0.17.2)
      waterdrop (>= 2.7.3, < 3.0.0)
      zeitwerk (~> 2.3)
    karafka-core (2.4.7)
      karafka-rdkafka (>= 0.17.6, < 0.19.0)
    karafka-rdkafka (0.18.1)
      ffi (~> 1.15)
      mini_portile2 (~> 2.6)
      rake (> 12)
    mini_portile2 (2.8.8)
    pg (1.5.9)
    rake (13.2.1)
    standalone_migrations (2.0.4)
      standalone_migrations
    waterdrop (2.8.0)
      karafka-core (>= 2.4.3, < 3.0.0)
      karafka-rdkafka (>= 0.17.5)
      zeitwerk (~> 2.3)
    zeitwerk (2.7.1)

PLATFORMS
  aarch64-linux-gnu
  aarch64-linux-musl
  arm-linux-gnu
  arm-linux-musl
  arm64-darwin
  ruby
  x86-linux-gnu
  x86-linux-musl
  x86_64-darwin
  x86_64-linux-gnu
  x86_64-linux-musl

DEPENDENCIES
  karafka
  pg
  standalone_migrations

BUNDLED WITH
   2.5.14
```

Installation Method 
> bundler

Environment 
> development

Reproduction Steps 
> bundle exec karafka s

**Comment by mensfeld** [comment]
Line 6 of your stacktrace is:
`Bundler.require(:default, ENV['KARAFKA_ENV'])`

which would indicate rails is part of something somewhere you actually use and it fails on karafka because it runs bundler require. This is not karafka related but your setup/configuration/whatever related and I cannot reproduce it.
Please create a reproduction that I can review and run. **Not** instructions but a reproduction that allows to reproduce.

**Comment by mensfeld** [comment]
also you did **not** provide me with your docker setup so I cannot check it as well :shrug: 

as much as I like helping people and I do my best, I do expect same level of involvement from the other party.

**Comment by ksimmi** [comment]
> If you want this to be further investigated please create a reproduction based on this example app

My app is already the copy of your example app. I started from your example, after that I just removed some consumers like XmlMessagesConsumer, CountersConsumer PIngConsumer. Also I created PingProducer in another application because I want to send 'ping' message from my main app.  

> Line 6 of your stacktrace is:
> Bundler.require(:default, ENV['KARAFKA_ENV'])

The same as in your example-apps/v2.4-non-rails/karafka.rb

> ...which would indicate rails is part of something somewhere you actually use...

I'm not sure I understand how you reached that conclusion.

My docker setup
Dockerfile
```
ARG RUBY_VERSION=3.2.2
FROM registry.docker.com/library/ruby:$RUBY_VERSION-slim as base

WORKDIR /app

# Set Bundler path for volume
ENV BUNDLE_PATH="/usr/local/bundle"

# Copy required scripts
COPY dockerized/*.sh /bin

# Install env
RUN /bin/docker-apt-install.sh \
    build-essential libpq-dev libyaml-dev zlib1g-dev imagemagick \
    file shared-mime-info git curl python3 nodejs npm

# Update npm to latest version
RUN npm i -g npm

RUN gem install bundler
RUN gem install async-websocket
RUN gem install falcon

EXPOSE 7070

ENTRYPOINT ["/bin/docker-entrypoint.sh"]
```

docker_compose 
**I would like to draw your attention to the fact that I have removed the parts of the configuration file related to the main application.**
```
version: '3.9'

services:

  karafka_service:
    env_file:
      - handler_app/.env.dev
    build:
      context: .
      dockerfile: Dockerfile
    container_name: karafka_service
    environment:
      KAFKA_HOST: kafka:9092
    command: bash -c "bundle exec karafka s"
    stdin_open: true
    depends_on:
      - zookeeper
      - kafka
    tty: true
    volumes:
      - ./karafka_service:/app
      - rubygems_karafka_service:/usr/local/bundle
     
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


volumes:
  rubygems_karafka_service:
```

.env.dev
```
kafka_url=kafka:9092
```
