### ISSUE TITLE
Broker transport failure

### ISSUE THREAD

**Issue by ElenaSukhorukova** [karafka/karafka#2458]
Hi! Please help me with an error:
```
core(dev)> Karafka.producer.produce_sync(topic: 'users', payload: { 'ping' => 'pong' }.to_json)
[waterdrop-a60bc1a82835] Error occurred: Local: Broker transport failure (transport) - librdkafka.error
rdkafka: [thrd:dockervm:9092/1001]: dockervm:9092/1001: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 2ms in state CONNECT)
```
I have docker compose services:
```
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: "INTERNAL://kafka:9090,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:9090,EXTERNAL://dockervm:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
```
And I set configs in kafka.rb
```
class KarafkaApp < Karafka::App
  setup do |config|
    config.kafka = { 'bootstrap.servers': 'kafka:9092' }
    config.client_id = 'business_app'
    # Recreate consumers with each batch. This will allow Rails code reload to work in the
    # development mode. Otherwise Karafka process would not be aware of code changes
    config.consumer_persistence = !Rails.env.development?
  end
...
    topic :users do
      # Uncomment this if you want Karafka to manage your topics configuration
      # Managing topics configuration via routing will allow you to ensure config consistency
      # across multiple environments
      #
      # config(partitions: 2, 'cleanup.policy': 'compact')
      consumer ExampleConsumer
    end
  end
end
```

My etc/hosts includes
127.0.0.1 localhost
127.0.0.1 kafka
127.0.0.1 dockervm
