### ISSUE TITLE
Investigate lowering requirements on activesupport

### ISSUE THREAD

**Issue by mensfeld** [karafka/karafka#258]
We use a small subset of it, should be doable to support >= 4

**Comment by ronin** [comment]
I did the first trial on `activesupport (4.2.10)`. My app works ok, but after running karafka tests, two of them failed:

```
Failures:

  1) Karafka::Controllers::Callbacks when we want to use after_fetched callback when we have a block based after_fetched when it throws abort to halt does not consume
     Failure/Error: throw(:abort)

     UncaughtThrowError:
       uncaught throw :abort
     # ./spec/lib/karafka/controllers/callbacks_spec.rb:63:in `throw'
     # ./spec/lib/karafka/controllers/callbacks_spec.rb:63:in `block (7 levels) in <top (required)>'
     # ./lib/karafka/controllers/callbacks.rb:48:in `call'
     # ./spec/lib/karafka/controllers/callbacks_spec.rb:75:in `block (5 levels) in <top (required)>'

  2) Karafka::Controllers::Callbacks when we want to use after_fetched callback when we have a method based after_fetched when it throws abort to halt does not consume
     Failure/Error: throw(:abort)

     UncaughtThrowError:
       uncaught throw :abort
     # ./spec/lib/karafka/controllers/callbacks_spec.rb:123:in `throw'
     # ./spec/lib/karafka/controllers/callbacks_spec.rb:123:in `method'
     # ./lib/karafka/controllers/callbacks.rb:48:in `call'
     # ./spec/lib/karafka/controllers/callbacks_spec.rb:131:in `block (5 levels) in <top (required)>'

Finished in 0.68855 seconds (files took 0.69707 seconds to load)
```

I didn't have time yet to investigate it.
