### ISSUE TITLE
Multi-karafka environment making consumers read messages twice

### ISSUE THREAD

**Issue by brunoocasali** [karafka/karafka#611]
## Expected behavior

My deployment configuration today is in kubernetes, and I have one "deployment" for karafka and another for the app itself, the karafka deployment has a HPA which have 2 or more pods running the same karafka configuration.

So in another words I have two or more karafka servers running consuming the same topics, using the same consumer classes.

I expected to kafka/karafka balance messages between these two or more servers, so:
 - **message # 1** goes to **pod xyz**
 - **message # 2** goes to **pod abc** 
 - **message # 3** goes to any of them

## Actual behavior

Today the behaviour is:
 - **message # 1** goes to **pod xyz**
 - **message # 1** goes to **pod abc**
 - **message # 2** goes to **pod abc** 
 - **message # 2** goes to **pod xyz** 
 - **message # 3** goes to both

## Steps to reproduce the problem

I've recreated the settings in my local docker-compose config:

```yml
beta:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    image: moments:development
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - ~/.bash_history:/home/root/.bash_history
    command: bundle exec karafka server
    entrypoint: docker/development/entrypoint
    stdin_open: true
    tty: true
    env_file: config/env/development.env
    links:
      - db:database
    depends_on:
      - db
      - kafka

  alfa:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    command: bundle exec karafka server
    stdin_open: true
    tty: true
    env_file: config/env/development.env
    links:
      - db:database
    depends_on:
      - db
      - kafka
```

When i ran `docker-compose up` the both servers are running in parallel but they not work as if they are one. 

## Setup details

Each of running pod's have the same source code and the same karafka config:
```bash
$ bundle exec karafka info
Karafka version: 1.3.1
Ruby version: 2.6.3
Ruby-kafka version: 0.7.10
Application client id: moments
Backend: inline
Batch fetching: true
Batch consuming: false
Boot file: /app/karafka.rb
Environment: development
Kafka seed brokers: ["kafka://kafka.streaming.svc.cluster.local:9092"]
```

My karafka.rb
```rb
# ommited (because is the default config)

class KarafkaApp < Karafka::App
  setup do |config|
    config.kafka.seed_brokers = [Rails.application.config.kafka_url]
    config.client_id = 'moments'
    config.logger = Rails.logger

    # I've already tested mny combinations of these:
    # config.kafka.offset_commit_threshold = 10
    # config.batch_fetching = false
  end

  Karafka.monitor.subscribe(WaterDrop::Instrumentation::StdoutListener.new)
  Karafka.monitor.subscribe(Karafka::Instrumentation::StdoutListener.new)
  Karafka.monitor.subscribe(Karafka::Instrumentation::ProctitleListener.new)

  consumer_groups.draw do
    topic Rails.application.config.hermes_topics[:accomplishment].to_sym do
      consumer Hermes::AccomplishmentConsumer
    end
  end
end

Karafka.monitor.subscribe('app.initialized') do
end

KarafkaApp.boot!
```

My consumer:
```rb
module Hermes
  class AccomplishmentConsumer < ApplicationConsumer
    def consume
      Karafka.logger.error("start 'delivery_id': ------------>> #{delivery_id}")

      sleep 1

      Karafka.logger.error("end 'delivery_id': ------------>> #{delivery_id}")
    end
  end
end
```

```log
alfa_1       | [[moments_hermes-accomplished] {hermes-accomplished: 0}:] Reached max fetcher queue size (10), sleeping 1s
alfa_1       | end 'delivery_id': ------------>> 45
alfa_1       | Inline processing of topic hermes-accomplished with 1 messages took 1006 ms
alfa_1       | Params deserialization for hermes-accomplished topic successful in 0 ms
alfa_1       | start 'delivery_id': ------------>> 46
beta_1       | [[moments_hermes-accomplished] {hermes-accomplished: 0}:] Reached max fetcher queue size (10), sleeping 1s
beta_1       | end 'delivery_id': ------------>> 81
beta_1       | Inline processing of topic hermes-accomplished with 1 messages took 1005 ms
beta_1       | Params deserialization for hermes-accomplished topic successful in 0 ms
beta_1       | start 'delivery_id': ------------>> 82
```

After some time the "alfa" server will process the "message with delivery_id #82" even if the "beta" already processed that message.

Thanks in advance for your time!

**Comment by mensfeld** [comment]
@brunoocasali is there a reason for you to use such an old version of ruby-kafka?

```
Ruby-kafka version: 0.7.10
```

current one is `1.2.0`. 

I'm not saying it's this but a lof ot things have changed and many things were fixed so lets tackle that one issue a time, ok?

**Comment by brunoocasali** [comment]
Actually not, I will update and test it!

**Comment by brunoocasali** [comment]
Unfortunately the same behaviour happen!

```bash
bash-5.0# bundle exec karafka info
Initializing Karafka server 27
Karafka version: 1.3.7
Ruby version: 2.6.3
Ruby-kafka version: 1.2.0
Application client id: moments
Backend: inline
Batch fetching: true
Batch consuming: false
Boot file: /app/karafka.rb
Environment: development
Kafka seed brokers: ["kafka://kafka:9092"]
```

I didn't post before, but this log is happening too (even before the update):

```yml
beta_1       | Inline processing of topic hermes-accomplished with 1 messages took 304 ms
beta_1       | 100 messages on hermes-accomplished topic delegated to Hermes::AccomplishmentConsumer
beta_1       | [[moments_hermes-accomplished] {}:] Marking hermes-accomplished/0:199 as processed
beta_1       | [[moments_hermes-accomplished] {}:] Committing offsets: hermes-accomplished/0:200
beta_1       | [[moments_hermes-accomplished] {}:] [offset_commit] Sending offset_commit API request 18 to 6422c030ca04:9092
beta_1       | [[moments_hermes-accomplished] {}:] [offset_commit] Waiting for response 18 from 6422c030ca04:9092
beta_1       | [[moments_hermes-accomplished] {}:] [offset_commit] Received response 18 from 6422c030ca04:9092
beta_1       | [[moments_hermes-accomplished] {}:] Error committing offsets: Kafka::UnknownMemberId
beta_1       | [[moments_hermes-accomplished] {}:] Joining group `moments_hermes-accomplished`
beta_1       | [[moments_hermes-accomplished] {}:] [join_group] Sending join_group API request 19 to 6422c030ca04:9092
beta_1       | [[moments_hermes-accomplished] {}:] [join_group] Waiting for response 19 from 6422c030ca04:9092
beta_1       | [[moments_hermes-accomplished] {}:] [join_group] Received response 19 from 6422c030ca04:9092
beta_1       | [[moments_hermes-accomplished] {}:] Failed to join group; resetting member id and retrying in 1s...
alfa_1       | [[moments_hermes-accomplished] {}:] No batches to process
```

Maybe is related to the main issue?

**Comment by mensfeld** [comment]
this is:

```
beta_1       | [[moments_hermes-accomplished] {}:] Error committing offsets: Kafka::UnknownMemberId
```

This can mean many things but generally, it can mean couple things:

- https://issues.apache.org/jira/browse/KAFKA-8653 (if you have a version of Kafka with this regression)
- your messages are consumed way too long. You should switch batch consuming off or tune `max_wait_time` to fetch smaller batches so you don't end up processing longer than the `session_timeout`.

Session timeout is the number of seconds after which, if a client hasn't contacted the Kafka cluster, it will be kicked out of the group.

Karafka 2.0 will have a different design for this, but meanwhile, you can try the advice above or you can tune the `heartbeat_interval` as well.

**Comment by mensfeld** [comment]
@brunoocasali did it help?

**Comment by brunoocasali** [comment]
@mensfeld the sample I've provided before is just an example, but the message really takes some time to process (more than 40s).

But in my tests I've changed to `batch_consuming = false` (as you suggested) and reduced to just a `sleep 0.3` (I think is a pretty reasonable number to simulate a real workload), and the same behaviour happen (both instances processing same message not in the same time).

If confirmed the hypothesis about the timing, I'll recreate my consumers to process small messages instead one taking a long time.

Btw my kafka docker-compose config is:
```yml
zookeeper:
    image: zookeeper:3.5.6
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog

  kafka:
    image: confluentinc/cp-kafka:5.3.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
    depends_on:
      - zookeeper
```

When I open this issue I think I have a misunderstood about something because I thought this was a common setting (multi instances running at the same time using the same config/source code), but apparently is not! So how we can achieve a fault tolerant configuration in a preemptible instances?

btw: thanks a lot for your time!
